# Generated by Django 2.2.5 on 2019-12-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kursved', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='id_vedom',
        ),
        migrations.CreateModel(
            name='studtovedom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Зач', 'Зачет'), ('Незач', 'Незачет'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5)),
                ('id_stud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kursved.stud')),
                ('id_vedom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kursved.vedom')),
            ],
        ),
    ]
