# Generated by Django 2.2.5 on 2019-12-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursved', '0002_auto_20191217_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studtovedom',
            old_name='id_stud',
            new_name='studname',
        ),
        migrations.RenameField(
            model_name='studtovedom',
            old_name='id_vedom',
            new_name='vedomname',
        ),
        migrations.AlterField(
            model_name='studtovedom',
            name='value',
            field=models.CharField(choices=[('Зач', 'Зачет'), ('Незач', 'Незачет'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
    ]
