# Generated by Django 2.2.5 on 2019-12-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursved', '0004_studtovedom_qwe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studtovedom',
            name='qwe',
        ),
    ]
