# Generated by Django 2.2.5 on 2019-12-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursved', '0005_remove_studtovedom_qwe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vedom',
            old_name='id_user',
            new_name='userid',
        ),
    ]
